[package]
name = "playdate-sys"
version = "0.1.0"
authors = ["Dan <igaryhe@gmail.com>"]
edition = "2018"

[dependencies]
cty = "0.2.1"

[build-dependencies]
bindgen = { version = "0.58", default-features = false, features = ["runtime"] }