[package]
name = "playdate"
version = "0.1.0"
authors = ["Dan <igaryhe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
playdate-sys = { path = "playdate-sys" }
anyhow = "1.0.34"
cstr_core = "0.2.2"

[workspace]
members = [
    "playdate-sys"
]

[lib]
crate-type = ["staticlib", "cdylib"]