[target.thumbv7em-none-eabihf]
rustflags = ["-C", "link-arg=-mthumb",
             "-C", "link-arg=-mcpu=cortex-m7",
             "-C", "link-arg=-mfloat-abi=hard",
             "-C", "link-arg=-mfpu=fpv4-sp-d16",
             "-C", "link-arg=-D__FPU_USED=1",
             "-C", "link-arg=-Tplaydate-sys/src/link_map.ld"]
linker = "arm-none-eabi-gcc"

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=/NOENTRY"]

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "alloc"]
